### ISSUE TITLE
small fix

### ISSUE THREAD

**Issue by ghost** [beaston02/CamsterRecorder#2]
The readme should read something like this
pip install livestreamer bs4 lxml 

Without the lxml package the program won't  run I don't t
I had some issues till I ran that command which came from the chaturbate package you have.

**Comment by beaston02** [comment]
Thank you for pointing that out. I updated the command in the readme to include lxml and gevent.

**Comment by ghost** [comment]
Not a big deal but only the lxml package is needed. 
I deleted all my packages and use 
pip install livestreamer bs4 lxml 

Edit: I have no idea what I'm talking about the chaturbate program also runs without that gevent 
package it seems. but maybe it is needed during the process. 

So maybe it better to leave it in for both programs 
Chaturbate and camster
